#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

HISTTIMEFORMAT='%Y-%m-%d%T '
PS1='[\u@\h \W]\$ '

alias ls='ls --color=auto'
alias lt='ls -lsrht'

alias cls='clear'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias lt='ls -lsht'
alias grep='grep --color=auto'

# Custom alias 
alias cb='sudo carbonara.sh'
alias pw='/bin/PipewireRestartAllServices.sh'
alias pws='/bin/PipewireCheckServices.sh'
alias lsblkd='lsblk --output=NAME,MODEL,PATH,FSAVAIL,FSROOTS,FSSIZE,FSTYPE,FSUSED,FSUSE%,FSVER,MOUNTPOINTS | grep -v loop '
alias cl='xsel -clipboard --clear; printf "\nclipboard was cleaner!\n"'
alias rb='clear; trash-empty --all; printf "Rubbish is clear!\n"'

# Enable command auto-completion
if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
fi

source /home/apollo/.config/broot/launcher/bash/br
export EDITOR=vim
